events {
    worker_connections 1024;
}

http {
    upstream gopher_cluster {
        server gopher-node-1:50051 max_fails=1 fail_timeout=10s;
        server gopher-node-2:50052 max_fails=1 fail_timeout=10s;
        server gopher-node-3:50053 max_fails=1 fail_timeout=10s;
        server gopher-node-4:50054 max_fails=1 fail_timeout=10s;
        server gopher-node-5:50055 max_fails=1 fail_timeout=10s;
    }

    server {
        listen 80 http2; 

        location / {
            grpc_pass grpc://gopher_cluster;
            grpc_next_upstream error timeout invalid_header http_500;
            grpc_next_upstream_tries 5;
            grpc_read_timeout 1s;
            grpc_connect_timeout 100ms; 
        }
    }
}