{
 "title": "Gopher-Guard Default Dashboards",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster Leadership",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "raft_is_leader", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate Limits Allowed vs Denied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(gopher_guard_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total gRPC Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}