services:
  gopher-guard:
    image: abhinavg786/gopher-guard:v1.1.0
    ports:
      - "50051:50051" # gRPC Port
      - "8080:8080"   # Admin/Join Port
    environment:
      - PORT=50051
      - ADMIN_PORT=8080
      - NODE_ID=node-1
      - BOOTSTRAP=true
      - RAFT_BIND=0.0.0.0:7000